# ===============================
# APP CONFIG
# ===============================
spring.application.name=shopflow
server.port=8080

# ===============================
# INTERNATIONALISATION (Français)
# ===============================
spring.messages.basename=messages
spring.messages.encoding=UTF-8
spring.web.locale=fr_TN
spring.web.locale-resolver=fixed

# ===============================
# DATABASE (PostgreSQL)
# ===============================
spring.datasource.url=jdbc:postgresql://localhost:5433/shopflow
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

# ===============================
# JPA / HIBERNATE
# ===============================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.jdbc.time_zone=UTC

# IMPORTANT (�vite erreurs Lazy)
spring.jpa.open-in-view=false

# ===============================
# JWT
# ===============================
jwt.secret=404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
jwt.expiration=86400000
jwt.refreshExpiration=604800000

# ===============================
# SWAGGER / OPENAPI
# ===============================
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/v3/api-docs

# ===============================
# FILE UPLOAD & POST LIMITS
# ===============================
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=50MB
server.tomcat.max-http-post-size=50MB
server.tomcat.max-swallow-size=-1

# ===============================
# LOGGING (optionnel mais pro)
# ===============================
logging.level.org.springframework.security=DEBUG
logging.level.org.hibernate.SQL=DEBUG

spring.main.allow-bean-definition-overriding=true
spring.jpa.show-sql=true